### ISSUE TITLE
opendevops

### ISSUE THREAD

**Issue by yanghongfei** [pycook/cmdb#23]
作者你好：

有兴趣参与opendevops开源项目?

https://www.opendevops.cn/
https://github.com/opendevops-cn/opendevops

可以了解下，感谢你对开源做的贡献。

**Comment by pycook** [comment]
你好，谢谢你的关注，因为现在精力比较有限，只能业余时间来做，我打算目前专注于cmdb。

我会关注你们的开源项目，有机会的话会在何时的时候参与进来
