### ISSUE TITLE
勉强装起来了。。数据库也执行了。。但是数据库里面空空的。。啥都没。。自己创建了一个用户。没权限无法自定义模型。。。

### ISSUE THREAD

**Issue by smile-wang** [pycook/cmdb#7]
勉强装起来了。。数据库也执行了。。但是数据库里面空空的。。啥都没。。自己创建了一个用户。没权限无法自定义模型。。。

**Comment by pycook** [comment]
你在roles表里创建个admin的role 然后在users_roles表里关联上你的用户和admin role

注意password要设置md5值 ， is_block设置为0

**Comment by smile-wang** [comment]
按照你的要求  加上了  is_block设置为0   但是还是没办法创建 模型定义。

**Comment by smile-wang** [comment]
http://139.9.185.24:8000/

用户密码 都是admin

**Comment by pycook** [comment]
你可以留个邮箱否

**Comment by smile-wang** [comment]
hongbin.wang@live.com
