### ISSUE TITLE
修改那个文件才能更改访问IP。。

### ISSUE THREAD

**Issue by smile-wang** [pycook/cmdb#9]
修改那个文件才能更改访问IP。。

貌似现在这个访问IP的绑定 直接是自动选择绑定网卡的。。。太难了。。vue ..

我是  云服务器。。他指向的是内网IP 。。。我在运行的时候加 0.0.0.0  访问的时候 任然有内网链接。。
请问如何解决

**Comment by smile-wang** [comment]
App running at:
  - Local:   http://localhost:8000/ 
  - Network: http://192.168.0.226:8000/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

**Comment by pycook** [comment]
公有云建议用nginx做反向代理
